[7875]
Host = "6.tcp.eu.ngrok.io"
Port = "12485"
User = "root"
Password = "mysql"
Databases = "atliq_tshirts"

[231]
Host = "localhost"
Port = "3306"
User = "root"
Password = "mysql"
Databases = "atliq_tshirts"
